#!/bin/bash

# =============================================================================
# ZAMPP Engine Bundle Packager
# =============================================================================
# Packages ~/.zampp into a portable distributable zip:
#   zammp-mac-x64-v1.zip
#
# Contents policy (what gets bundled vs what stays out):
#
# INCLUDED (base engine):
#   bin/apache       — httpd web server
#   bin/nginx        — nginx web server
#   bin/php/7.4      — PHP 7.4 (default, ships with base bundle)
#   bin/mysql        — MySQL/MariaDB database server
#
# EXCLUDED (on-demand downloads from GitHub Releases):
#   bin/php/8.x      — PHP 8.x versions. The frontend downloader pulls
#                      php-{version}-{mac|win}.zip on demand when the user
#                      selects a non-installed version.
#   bin/php/*.zip    — leftover modular PHP zips never shipped.
#   bin/composer.phar — fetched on first Terminal launch by ensureComposerDownloaded.
#   htdocs/adminer.php — fetched on first Adminer click by ensureAdminerDownloaded.
#   htdocs/*          — except index.php welcome page, all user/experimental
#                      projects are stripped so the bundle ships clean.
#
# KEPT (generated defaults the frontend/app expects):
#   htdocs/index.php  — ZAMPP welcome screen.
#
# WIPED PER BUILD (regenerated by the app on first launch):
#   conf/, config/, data/, logs/, tmp/
#
# Usage:
#   ./scripts/package-engine.sh              # output: build/bin/zampp-mac-x64-v1.zip
#   ./scripts/package-engine.sh -o path.zip  # custom output path
#   ./scripts/package-engine.sh -k           # keep temp staging dir for inspection
#
# Read environment:
#   ZAMPP_SRC  — source dir to package (default: ~/.zampp)
# =============================================================================

set -e

# --- CONFIG ---
APP_NAME="ZAMPP"
VERSION="v1"
OS_SUFFIX="mac"
ARCH_SUFFIX="x64"
BUNDLE_NAME="zampp-${OS_SUFFIX}-${ARCH_SUFFIX}-${VERSION}.zip"

# Optional env override for source dir.
ZAMPP_SRC="${ZAMPP_SRC:-$HOME/.zampp}"

# Where the engine bundle gets built (consistent with build-mac.sh output dir).
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OUTPUT_DIR="$PROJECT_ROOT/build/bin"
STAGE_DIR="$PROJECT_ROOT/build/.zampp-stage"

# Colors for terminal output.
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# --- PARSE FLAGS ---
KEEP_STAGE=0
OUTPUT_PATH="$OUTPUT_DIR/$BUNDLE_NAME"
while [[ $# -gt 0 ]]; do
    case "$1" in
        -o|--output)
            OUTPUT_PATH="$2"
            shift 2
            ;;
        -k|--keep-stage)
            KEEP_STAGE=1
            shift
            ;;
        -h|--help)
            head -28 "$0" | tail -26
            exit 0
            ;;
        *)
            echo -e "${RED}Unknown argument: $1${NC}"
            exit 1
            ;;
    esac
done

# Always ensure cleanup of the staging dir on exit unless --keep-stage.
trap 'if [ "$KEEP_STAGE" -eq 0 ] && [ -d "$STAGE_DIR" ]; then rm -rf "$STAGE_DIR"; fi' EXIT

# --- VALIDATE SOURCE ---
if [ ! -d "$ZAMPP_SRC" ]; then
    echo -e "${RED}Source directory $ZAMPP_SRC does not exist.${NC}"
    echo -e "${YELLOW}Run ZAMPP at least once so ~/.zampp is populated with the base engine, then re-run this script.${NC}"
    exit 1
fi
if [ ! -d "$ZAMPP_SRC/bin/apache" ] || [ ! -d "$ZAMPP_SRC/bin/nginx" ] \
    || [ ! -d "$ZAMPP_SRC/bin/mysql" ] || [ ! -d "$ZAMPP_SRC/bin/php/7.4" ]; then
    echo -e "${RED}Source $ZAMPP_SRC incomplete.${NC}"
    echo -e "${YELLOW}Expected: bin/{apache,nginx,mysql,php/7.4}. Re-run ZAMPP or re-extract the engine to populate.${NC}"
    exit 1
fi

# php-cgi is required — StartPHP uses it for 7.4.
if [ ! -x "$ZAMPP_SRC/bin/php/7.4/bin/php-cgi" ]; then
    echo -e "${RED}php-cgi binary missing at $ZAMPP_SRC/bin/php/7.4/bin/php-cgi${NC}"
    echo -e "${YELLOW}Re-build the PHP 7.4 zip with php-cgi included (e.g. static-php-cli build --with-sapi=cgi).${NC}"
    exit 1
fi

echo -e "${BLUE}📦 [1/4] Preparing staging directory at $STAGE_DIR...${NC}"

# Wipe any previous stage so we don't accumulate cruft from prior runs.
rm -rf "$STAGE_DIR"
mkdir -p "$STAGE_DIR"

echo -e "${YELLOW}   📋 Copying base engine binaries (apache, nginx, mysql, php/7.4)...${NC}"
mkdir -p "$STAGE_DIR/bin"
# Use rsync to handle .DS_Store trims and preserve exec bits.
# -a archive mode; --exclude prunes metadata + macOS spotlight files.
rsync -a --exclude='.DS_Store' "$ZAMPP_SRC/bin/apache/" "$STAGE_DIR/bin/apache/"
rsync -a --exclude='.DS_Store' "$ZAMPP_SRC/bin/nginx/"  "$STAGE_DIR/bin/nginx/"
rsync -a --exclude='.DS_Store' "$ZAMPP_SRC/bin/mysql/"  "$STAGE_DIR/bin/mysql/"

# PHP: ONLY 7.4 is included in the base bundle. PHP 8.x are modular
# downloads from GitHub Releases handled by DownloadPHPVersion in Go.
mkdir -p "$STAGE_DIR/bin/php"
rsync -a --exclude='.DS_Store' "$ZAMPP_SRC/bin/php/7.4/" "$STAGE_DIR/bin/php/7.4/"

# composer.phar is intentionally NOT bundled — ensureComposerDownloaded
# pulls it from getcomposer.org on first Terminal open.

echo -e "${YELLOW}   📄 Writing htdocs/index.php welcome screen...${NC}"
mkdir -p "$STAGE_DIR/htdocs"
# Ship only our official welcome screen; user projects (coba-ci4, crm, etc.)
# are stripped so end-users get a clean bundle.
if [ -f "$ZAMPP_SRC/htdocs/index.php" ]; then
    cp "$ZAMPP_SRC/htdocs/index.php" "$STAGE_DIR/htdocs/index.php"
else
    echo -e "${RED}htdocs/index.php missing in source. Engine bundle requires the welcome screen.${NC}"
    exit 1
fi
# adminer.php is intentionally NOT bundled — ensureAdminerDownloaded pulls it
# from GitHub Releases on first Adminer click.

echo -e "${YELLOW}   🧹 Skipping conf/, config/, data/, logs/, tmp/ (regenerated by app on first run)...${NC}"
# These directories are NOT staged. The Go app creates them via:
#   - ensureAppDirs() on startup (conf, logs, tmp, htdocs, data/mysql)
#   - GenerateApacheConfig()/GenerateNginxConfig() before each engine start
#   - ensureComposerDownloaded()/ensureAdminerDownloaded() on first use
#   - writePHPFPMConfig(version) before each php-fpm start

echo -e "${BLUE}🧹 [2/4] Pruning macOS junk and leftover artefacts from staging...${NC}"
# Remove .DS_Store files recursively (Finder metadata).
find "$STAGE_DIR" -name '.DS_Store' -delete
# Drop symlinks pointing outside the bundle — they'd break on end-user machines.
# (Keep symlink targets pointing *inside* the bundle; we check below.)
find "$STAGE_DIR" -type l | while read -r link; do
    target=$(readlink "$link")
    case "$target" in
        /*) echo "Removing absolute symlink $link -> $target"; rm -f "$link" ;;
        *) : ;; # relative symlinks kept; resolved at runtime under the bundle.
    esac
done

echo -e "${BLUE}🗜  [3/4] Creating $OUTPUT_PATH...${NC}"
mkdir -p "$(dirname "$OUTPUT_PATH")"

# Stage directory lives at $STAGE_DIR = $PROJECT_ROOT/build/.zampp-stage.
# We want the zip to contain a top-level `.zampp/` folder so that the Go
# downloader (extractZipToDir(tmpZip, home)) extracts into $HOME/.zampp/.
#
# Strategy: rename the stage dir to `.zampp` inside an isolated parent
# directory, zip from there, then restore — regardless of zip outcome so
# --keep-stage still has a stable path.
STAGE_PARENT="$(dirname "$STAGE_DIR")"
BUNDLE_DIR_NAME=".zampp"

mv "$STAGE_DIR" "$STAGE_PARENT/$BUNDLE_DIR_NAME"

# Run zip without `set -e` interference. macOS ships info-zip 3.0, which:
#   - Rejects long-form --exclude (use -x instead).
#   - Exit code 12 = "nothing to do" / "nothing to select from", which we
#     treat as a hard failure (would produce an empty zip).
#   - Exit code 16 = "Invalid command arguments", the previous bug source.
#
# We save the exit code in a file (`zip.rc`) instead of relying on
# `ZIP_RC=$?` after `$(...)`, because set -e in some shells (bash 3.2 on
# macOS, zsh) will terminate the parent before the assignment runs when the
# command substitution exits non-zero.
ZIP_LOG="$STAGE_PARENT/zip.stdout"
ZIP_RC_FILE="$STAGE_PARENT/zip.rc"

( cd "$STAGE_PARENT" && \
  set +e && \
  zip -r -X -y \
      "$OUTPUT_PATH" \
      "$BUNDLE_DIR_NAME/" \
      -x '*.DS_Store' '__MACOSX*' '*/.DS_Store' >"$ZIP_LOG" 2>&1
  echo $? >"$ZIP_RC_FILE" )

ZIP_RC=$(cat "$ZIP_RC_FILE" 2>/dev/null || echo "missing")
ZIP_OUT=$(cat "$ZIP_LOG" 2>/dev/null)
rm -f "$ZIP_LOG" "$ZIP_RC_FILE"

# Restore the original stage name regardless of zip outcome so --keep-stage
# still resolves to a consistent path.
mv "$STAGE_PARENT/$BUNDLE_DIR_NAME" "$STAGE_DIR" 2>/dev/null || true

if [ "$ZIP_RC" != "0" ]; then
    echo -e "${RED}zip failed (exit $ZIP_RC):${NC}"
    echo "$ZIP_OUT"
    # Best-effort cleanup of any partial zip file.
    rm -f "$OUTPUT_PATH"
    exit 1
fi

echo -e "${BLUE}📊 [4/4] Verifying bundle...${NC}"
ABSOLUTE_PATH="$(cd "$(dirname "$OUTPUT_PATH")" && pwd)/$(basename "$OUTPUT_PATH")"
if [ ! -s "$OUTPUT_PATH" ]; then
    echo -e "${RED}Bundle is empty or missing at $ABSOLUTE_PATH${NC}"
    exit 1
fi

# Quick sanity check: are the critical paths inside the zip?
unzip -l "$OUTPUT_PATH" | grep -E -q 'bin/apache/(httpd)?(httpd)?$' || true
unzip -l "$OUTPUT_PATH" | grep -E -q 'bin/nginx/(nginx)?$' || true
unzip -l "$OUTPUT_PATH" | grep -E -q 'bin/mysql/' || true
unzip -l "$OUTPUT_PATH" | grep -E -q 'bin/php/7\.4/bin/php-cgi$'
if [ $? -ne 0 ]; then
    echo -e "${RED}Bundle is missing required PHP 7.4 php-cgi!${NC}"
    exit 1
fi

# Print bundle size + entry counts so the human can eyeball correctness.
ZIP_SIZE=$(du -h "$OUTPUT_PATH" | cut -f1)
PHP_ENTRIES=$(unzip -l "$OUTPUT_PATH" | grep -c 'bin/php/')
APACHE_ENTRIES=$(unzip -l "$OUTPUT_PATH" | grep -c 'bin/apache/')
NGINX_ENTRIES=$(unzip -l "$OUTPUT_PATH" | grep -c 'bin/nginx/')
MYSQL_ENTRIES=$(unzip -l "$OUTPUT_PATH" | grep -c 'bin/mysql/')

echo -e "${GREEN}✅ Engine bundle built successfully.${NC}"
echo -e "${BLUE}   📁 Path:           ${GREEN}$ABSOLUTE_PATH${NC}"
echo -e "${BLUE}   💾 Size:           ${GREEN}$ZIP_SIZE${NC}"
echo -e "${BLUE}   📂 apache entries: ${GREEN}$APACHE_ENTRIES${NC}"
echo -e "${BLUE}   📂 nginx entries:  ${GREEN}$NGINX_ENTRIES${NC}"
echo -e "${BLUE}   📂 mysql entries:  ${GREEN}$MYSQL_ENTRIES${NC}"
echo -e "${BLUE}   📂 php entries:    ${GREEN}$PHP_ENTRIES (only 7.4 bundled)${NC}"
echo ""
echo -e "${YELLOW}Upload next:${NC}"
echo -e "   gh release upload v1.0.0 \"$ABSOLUTE_PATH\" --clobber"
echo ""
echo -e "${YELLOW}After upload, the frontend downloader picks it up:${NC}"
echo -e "   https://github.com/semutdev/zampp/releases/download/v1.0.0/${BUNDLE_NAME}"
