// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckFirstRun() {
  return window['go']['main']['App']['CheckFirstRun']();
}

export function CheckPHPVersion(arg1) {
  return window['go']['main']['App']['CheckPHPVersion'](arg1);
}

export function DownloadAndExtractBinaries() {
  return window['go']['main']['App']['DownloadAndExtractBinaries']();
}

export function DownloadPHPVersion(arg1) {
  return window['go']['main']['App']['DownloadPHPVersion'](arg1);
}

export function GetInstalledVersions() {
  return window['go']['main']['App']['GetInstalledVersions']();
}

export function IsApacheInstalled() {
  return window['go']['main']['App']['IsApacheInstalled']();
}

export function IsMySQLInstalled() {
  return window['go']['main']['App']['IsMySQLInstalled']();
}

export function IsNginxInstalled() {
  return window['go']['main']['App']['IsNginxInstalled']();
}

export function OpenAdminer() {
  return window['go']['main']['App']['OpenAdminer']();
}

export function OpenHtdocsFolder() {
  return window['go']['main']['App']['OpenHtdocsFolder']();
}

export function OpenWebRoot() {
  return window['go']['main']['App']['OpenWebRoot']();
}

export function StartApache() {
  return window['go']['main']['App']['StartApache']();
}

export function StartMySQL() {
  return window['go']['main']['App']['StartMySQL']();
}

export function StartNginx() {
  return window['go']['main']['App']['StartNginx']();
}

export function StartPHP(arg1) {
  return window['go']['main']['App']['StartPHP'](arg1);
}

export function StartWebServer(arg1, arg2) {
  return window['go']['main']['App']['StartWebServer'](arg1, arg2);
}

export function StopApache() {
  return window['go']['main']['App']['StopApache']();
}

export function StopMySQL() {
  return window['go']['main']['App']['StopMySQL']();
}

export function StopNginx() {
  return window['go']['main']['App']['StopNginx']();
}

export function StopPHP() {
  return window['go']['main']['App']['StopPHP']();
}

export function StopWebServer(arg1) {
  return window['go']['main']['App']['StopWebServer'](arg1);
}
