// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetInstalledVersions():Promise<Array<string>>;

export function IsApacheInstalled():Promise<boolean>;

export function IsMySQLInstalled():Promise<boolean>;

export function IsNginxInstalled():Promise<boolean>;

export function OpenAdminer():Promise<string>;

export function OpenHtdocsFolder():Promise<void>;

export function OpenWebRoot():Promise<string>;

export function StartApache():Promise<string>;

export function StartMySQL():Promise<string>;

export function StartNginx():Promise<string>;

export function StartPHP(arg1:string):Promise<string>;

export function StartWebServer(arg1:string,arg2:string):Promise<string>;

export function StopApache():Promise<string>;

export function StopMySQL():Promise<string>;

export function StopNginx():Promise<string>;

export function StopPHP():Promise<string>;

export function StopWebServer(arg1:string):Promise<string>;
